### ISSUE TITLE
fails to export

### ISSUE THREAD

**Issue by ac427** [GoogleCloudPlatform/otlp-k8s-ingest#56]
I followed the exact steps in the readme, but I see below in collector logs

```
{"level":"info","ts":"2025-04-30T17:56:53.794Z","caller":"otlpreceiver@v0.122.1/otlp.go:116","msg":"Starting GRPC server","otelcol.component.id":"otlp/self-metrics","otelcol.component.kind":"Receiver","endpoint":"10.46.2.189:14317"}
{"level":"info","ts":"2025-04-30T17:56:53.794Z","caller":"healthcheck/handler.go:132","msg":"Health Check state change","otelcol.component.id":"health_check","otelcol.component.kind":"Extension","status":"ready"}
{"level":"info","ts":"2025-04-30T17:56:53.794Z","caller":"service@v0.122.1/service.go:283","msg":"Everything is ready. Begin running and processing data."}
{"level":"warn","ts":"2025-04-30T17:57:53.772Z","caller":"grpc@v1.71.0/clientconn.go:1406","msg":"[core] [Channel #1 SubChannel #12]grpc: addrConn.createTransport failed to connect to {Addr: \"10.46.2.189:14317\", ServerName: \"10.46.2.189:14317\", }. Err: connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\"","grpc_log":true}
```

I did ran `gcloud projects add-iam-policy-binding ` ,  have required env set and applied using kustomize
```
 env | egrep "NUM|GOOGLE" | awk -F= '{print $1}'
GOOGLE_CLOUD_PROJECT
PROJECT_NUMBER
kubectl kustomize ./otlp-k8s-ingest/k8s/base | envsubst | kubectl apply -f -

**Comment by michaelrode** [comment]
I am having the same issue

**Comment by kylecacciatore** [comment]
I hate to pile-on, but I'm having the same issue as well, and I've been unable to find out more about this part of the configuration. Some help would be appreciated - thanks!

**Comment by cyberbudy** [comment]
I am having the same issue

**Comment by kylecacciatore** [comment]
I think I've found how to address it. Change the self-metrics configuration to use http instead of grpc.

Update the receiver:

```
      otlp/self-metrics:
        protocols:
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: ${env:MY_POD_IP}:14317
```

and the service telemetry

```
        metrics:
          readers:
          - periodic:
              exporter:
                otlp:
                  protocol: http/protobuf
                  endpoint: http://${env:MY_POD_IP}:14317
```
